apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: hms-dev
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: suryaa112003/appointment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: appointment-service-config
        - secretRef:
            name: appointment-service-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 15
          periodSeconds: 10
